// <auto-generated />
using HealthSQLDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthSQLDB.Migrations
{
    [DbContext(typeof(HealthContext))]
    [Migration("20200514084600_NewSicknessFromAnja")]
    partial class NewSicknessFromAnja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthCore.Domain.Model.Ailment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ailments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Covid-19"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manflu"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Broken bone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "tyfus"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Stubed Tow"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Depression"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Chinkunguya"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ebola"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Krim-Kongo-feber"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Lassafeber"
                        },
                        new
                        {
                            Id = 11,
                            Name = "MERS"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Nipahvirus"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Zikafeber"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Flu"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fat liver"
                        });
                });

            modelBuilder.Entity("HealthCore.Domain.Model.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Man up"
                        },
                        new
                        {
                            Id = 2,
                            Name = "No Cure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ibux"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sunshine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kondoms"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Scream"
                        },
                        new
                        {
                            Id = 7,
                            Name = "HPV vaksine"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ice cream"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Hug"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Antibiotics"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Flushoot"
                        });
                });

            modelBuilder.Entity("HealthCore.Domain.Model.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Name = "Ola Nordmann"
                        });
                });

            modelBuilder.Entity("HealthCore.Domain.Model.PatientAilments", b =>
                {
                    b.Property<int>("AilmentId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("AilmentId", "PatientId");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientAilments");

                    b.HasData(
                        new
                        {
                            AilmentId = 1,
                            PatientId = 1
                        });
                });

            modelBuilder.Entity("HealthCore.Domain.Model.PatientMedications", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("Doses")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "MedicationId");

                    b.HasIndex("MedicationId");

                    b.ToTable("PatientMedications");
                });

            modelBuilder.Entity("HealthCore.Domain.Model.PatientAilments", b =>
                {
                    b.HasOne("HealthCore.Domain.Model.Ailment", "Ailment")
                        .WithMany("PatientAilments")
                        .HasForeignKey("AilmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCore.Domain.Model.Patient", "Patient")
                        .WithMany("PatientAilments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HealthCore.Domain.Model.PatientMedications", b =>
                {
                    b.HasOne("HealthCore.Domain.Model.Medication", "Medication")
                        .WithMany("PatientMedications")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthCore.Domain.Model.Patient", "Patient")
                        .WithMany("PatientMedications")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
